### ISSUE TITLE
Install Issue on Kali Rolling Latest

### ISSUE THREAD

**Issue by dsgntech** [MetaChar/Mercury#1]
Hello, I'm getting an error when trying to install on Kali Rolling fully updated. PIP cannot find urllib2 to install, and then when trying to run Mercury.py, I get further errors, all attached below. Any recommendations? Thank you. 

pip install urllib2
Collecting urllib2
  Could not find a version that satisfies the requirement urllib2 (from versions: )
No matching distribution found for urllib2

 Do you have all of the needed Modules ?
Would You Like To Install Them Now? y/n: y
Requirement already satisfied: selenium in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: colorama in /usr/lib/python2.7/dist-packages
Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages
Collecting urllib2
  Could not find a version that satisfies the requirement urllib2 (from versions: )
No matching distribution found for urllib2
Collecting os
  Could not find a version that satisfies the requirement os (from versions: )
No matching distribution found for os
Collecting urllib
  Could not find a version that satisfies the requirement urllib (from versions: )
No matching distribution found for urllib
Requirement already satisfied: pygoogling in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: bs4 in /usr/local/lib/python2.7/dist-packages (from pygoogling)
Requirement already satisfied: html5lib in /usr/lib/python2.7/dist-packages (from pygoogling)
Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages (from pygoogling)
Requirement already satisfied: beautifulsoup4 in /usr/lib/python2.7/dist-packages (from bs4->pygoogling)
Collecting hashlib
  Using cached https://files.pythonhosted.org/packages/74/bb/9003d081345e9f0451884146e9ea2cff6e4cc4deac9ffd4a9ee98b318a49/hashlib-20081119.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 12, in <module>
        import setuptools.version
      File "/usr/lib/python2.7/dist-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 36, in <module>
        import email.parser
      File "/usr/lib/python2.7/email/parser.py", line 12, in <module>
        from email.feedparser import FeedParser
      File "/usr/lib/python2.7/email/feedparser.py", line 27, in <module>
        from email import message
      File "/usr/lib/python2.7/email/message.py", line 16, in <module>
        import email.charset
      File "/usr/lib/python2.7/email/charset.py", line 13, in <module>
        import email.base64mime
      File "/usr/lib/python2.7/email/base64mime.py", line 40, in <module>
        from email.utils import fix_eols
      File "/usr/lib/python2.7/email/utils.py", line 27, in <module>
        import random
      File "/usr/lib/python2.7/random.py", line 49, in <module>
        import hashlib as _hashlib
      File "hashlib.py", line 115, in <module>
        f()
    TypeError: 'frozenset' object is not callable
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-etLnp9/hashlib/
Collecting smtplib
  Could not find a version that satisfies the requirement smtplib (from versions: )
No matching distribution found for smtplib
Requirement already satisfied: mechanize in /usr/lib/python2.7/dist-packages
Collecting subprocess
  Could not find a version that satisfies the requirement subprocess (from versions: )
No matching distribution found for subprocess
Requirement already satisfied: pygoogling in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: bs4 in /usr/local/lib/python2.7/dist-packages (from pygoogling)
Requirement already satisfied: html5lib in /usr/lib/python2.7/dist-packages (from pygoogling)
Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages (from pygoogling)
Requirement already satisfied: beautifulsoup4 in /usr/lib/python2.7/dist-packages (from bs4->pygoogling)
Traceback (most recent call last):
  File "Mercury.py", line 82, in <module>
    init(convert=True)
NameError: name 'init' is not defined

**Comment by MetaChar** [comment]
sometimes urllib2 is already installed with python @dsgntech
try to use pip2 install urllib2

**Comment by dsgntech** [comment]
No dice on the pip2 attempt. Tried the same for urllib, subprocess, os, smtplib. Took out that line in both the main script, and from requirements. But the other missing dependencies still cause it to fail.

**Comment by dsgntech** [comment]
Figured out some of it. All of the modules it's attempting to install are already included in Python. I tried removing the dependency error and installation included within the script, but get a syntax error related to the class color line.

**Comment by dsgntech** [comment]
Your latest commit fixed the issue. Have a separate one, but will open a new one for it, this can be closed.
