### ISSUE TITLE
kali 

### ISSUE THREAD

**Issue by xiaogei** [MetaChar/Mercury#5]
root@kali:~/Mercury# pip install -r requirements.txt

Requirement already satisfied: colorama in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Collecting hashlib (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/74/bb/9003d081345e9f0451884146e9ea2cff6e4cc4deac9ffd4a9ee98b318a49/hashlib-20081119.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 12, in <module>
        import setuptools.version
      File "/usr/lib/python2.7/dist-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 36, in <module>
        import email.parser
      File "/usr/lib/python2.7/email/parser.py", line 12, in <module>
        from email.feedparser import FeedParser
      File "/usr/lib/python2.7/email/feedparser.py", line 27, in <module>
        from email import message
      File "/usr/lib/python2.7/email/message.py", line 16, in <module>
        import email.charset
      File "/usr/lib/python2.7/email/charset.py", line 13, in <module>
        import email.base64mime
      File "/usr/lib/python2.7/email/base64mime.py", line 40, in <module>
        from email.utils import fix_eols
      File "/usr/lib/python2.7/email/utils.py", line 27, in <module>
        import random
      File "/usr/lib/python2.7/random.py", line 49, in <module>
        import hashlib as _hashlib
      File "hashlib.py", line 115, in <module>
        f()
    TypeError: 'frozenset' object is not callable
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-nx5BqD/hashlib/

---------------------------------------------------
root@kali:~/Mercury# python Mercury.py 
Traceback (most recent call last):
  File "Mercury.py", line 19, in <module>
    import wget
ImportError: No module named wget

**Comment by MetaChar** [comment]
fixing it now..

**Comment by xiaogei** [comment]
Fix it, please tell me, thank you.

**Comment by MetaChar** [comment]
Update Mercury I removed the module. 🎉🎉

**Comment by MetaChar** [comment]
Update Mercury I removed the module. 🎉🎉
